-- Fix v_tradeshows view to include ALL columns from the tradeshows table
-- This was causing data persistence issues - columns were being saved but not returned on fetch

-- Must drop and recreate because column order/count changed
DROP VIEW IF EXISTS public.v_tradeshows;

CREATE VIEW public.v_tradeshows AS
SELECT 
  id,
  name,
  location,
  start_date,
  end_date,
  booth_number,
  booth_size_id,
  booth_size,
  cost,
  management_company_id,
  management_company,
  attendees_included,
  total_attending,
  total_leads,
  event_type,
  virtual_platform_id,
  virtual_platform,
  virtual_platform_url,
  virtual_booth_url,
  registration_confirmed,
  attendee_list_received,
  shipping_info,
  tracking_number,
  shipping_cost,
  ship_to_site,
  ship_to_warehouse,
  shipping_cutoff,
  shipping_label_path,
  tracking_status,
  tracking_status_details,
  tracking_eta,
  tracking_last_updated,
  shipping_carrier_id,
  return_carrier_id,
  return_tracking_number,
  return_shipping_cost,
  return_ship_date,
  return_delivery_date,
  move_in_date,
  move_in_time,
  move_out_date,
  move_out_time,
  lead_capture_system_id,
  lead_capture_system,
  lead_capture_credentials,
  booth_to_ship,
  graphics_to_ship,
  utilities_booked,
  utilities_details,
  labor_booked,
  labor_company_id,
  labor_details,
  electrical_cost,
  labor_cost,
  internet_cost,
  standard_services_cost,
  has_speaking_engagement,
  speaking_details,
  sponsorship_details,
  hotel_id,
  hotel_name,
  hotel_address,
  hotel_confirmed,
  hotel_cost_per_night,
  hotel_confirmation_number,
  hotel_confirmation_path,
  show_agenda_url,
  show_agenda_pdf_path,
  agenda_content,
  event_portal_url,
  has_event_app,
  event_app_notes,
  vendor_packet_path,
  show_contact_name,
  decrypt_pii(show_contact_email) as show_contact_email,
  show_contact_phone,
  show_website,
  venue_id,
  venue_name,
  venue_address,
  packing_list_items,
  swag_items_enabled,
  swag_items_description,
  giveaway_item_enabled,
  giveaway_item_description,
  power_strip_count,
  tablecloth_type,
  packing_list_misc,
  general_notes,
  show_status,
  qualified_leads,
  meetings_booked,
  deals_won,
  revenue_attributed,
  post_show_notes,
  is_template,
  organization_id,
  created_by,
  created_at,
  updated_at
FROM public.tradeshows;

-- Ensure permissions
GRANT SELECT ON public.v_tradeshows TO authenticated;
